### ISSUE TITLE
Segfaults using reticulate

### ISSUE THREAD

**Issue by khaeru** [r-lib/testthat#1035]
For reasons that I won't dwell on, I am trying to debug an issue using Python from R, via reticulate: and then, from Python, using Java via JPype.

In this situation, R code that can be run directly causes a segfault when executed via testthat; see the demo below. Installing debug symbols for all three languages hasn't helped pin down the cause.

This is mainly a question, i.e.: is there something about the way testthat invokes test code which might cause such issues, and is there any way I can work around it?

Thanks in advance.

script.py:
```python
import jpype
jpype.startJVM(convertStrings=False)
print(jpype.isJVMStarted())
```
script.R:
```R
jpype <- reticulate::import("jpype")
jpype$startJVM(convertStrings = FALSE)
print(jpype$isJVMStarted())
```
test_script.R:
```R
test_that("JPype can be run within testthat", {
  jpype <- reticulate::import("jpype")
  jpype$startJVM(convertStrings = FALSE)
  print(jpype$isJVMStarted())

  # Succeeds to this point; segfault occurs on exit from the test function
})
```

demo.sh:
```sh
#!/bin/sh

# Version information
uname -a
lsb_release -rd
R --version
Rscript -e "packageVersion('reticulate')"
Rscript -e "packageVersion('testthat')"
Rscript -e "reticulate::py_config()"
python3 --version
pip3 list | grep JPype1
java --version

# JPype through Python
python3 script.py

# Python script through reticulate
Rscript -e "reticulate::source_python('script.py')"

# Same code in R → reticulate → Python → JPype → Java
Rscript script.R

# Using testthat; segfaults
Rscript -e "testthat::test_dir('.')"
```

demo.sh gives the output:
<details><summary>Output</summary>

```
$ ./demo.sh
Linux khaeru-laptop 5.4.0-28-generic #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Description:    Ubuntu 20.04 LTS
Release:        20.04
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

[1] ‘1.15’
[1] ‘2.3.2’
python:         /usr/bin/python3
libpython:      /usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so
pythonhome:     //usr://usr
version:        3.8.2 (default, Apr 27 2020, 15:53:34)  [GCC 9.3.0]
numpy:          /usr/lib/python3/dist-packages/numpy
numpy_version:  1.17.4

python versions found: 
 /usr/bin/python3
 /usr/bin/python
 /home/khaeru/.local/share/virtualenvs/013-PR_Ssd8n/bin/python
 /home/khaeru/.local/share/virtualenvs/pyam-test-KM4109s8/bin/python
Python 3.8.2
JPype1                        0.7.5              
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing)
True
True
[1] TRUE
✔ |  OK F W S | Context
⠏ |   0       | test_script[1] TRUE
Segmentation fault (core dumped)
```
</details>

<details><summary>GDB output</summary>

```
$ gdb Rscript
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from Rscript...
Reading symbols from /usr/lib/debug/.build-id/2e/9ec7c89eee84f0fa14b74c9e01068784d2fe95.debug...
(gdb) run -e "testthat::test_dir('.')"
Starting program: /usr/bin/Rscript -e "testthat::test_dir('.')"
process 1138044 is executing new program: /bin/bash
[Detaching after fork from child process 1138048]
[Detaching after fork from child process 1138049]
[Detaching after fork from child process 1138052]
process 1138044 is executing new program: /usr/lib/R/bin/exec/R
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3a62700 (LWP 1138071)]
[New Thread 0x7ffff1261700 (LWP 1138072)]
[New Thread 0x7fffeea60700 (LWP 1138073)]
[New Thread 0x7fffec25f700 (LWP 1138074)]
[New Thread 0x7fffe9a5e700 (LWP 1138075)]
[New Thread 0x7fffe725d700 (LWP 1138076)]
[New Thread 0x7fffe4a5c700 (LWP 1138077)]
[Detaching after vfork from child process 1138078]
[Detaching after vfork from child process 1138080]
[Detaching after vfork from child process 1138082]
[Detaching after vfork from child process 1138105]
[Detaching after vfork from child process 1138107]
[New Thread 0x7fffdcf4f700 (LWP 1138140)]
✔ |  OK F W S | Context
⠏ |   0       | test_script[Detaching after fork from child process 1138141]

Thread 1 "R" received signal SIGSEGV, Segmentation fault.
0x00007fffc2a5762d in ?? ()
(gdb) backtrace
#0  0x00007fffc2a5762d in ?? ()
#1  0x0000000000000206 in ?? ()
#2  0x00007fffc2a57380 in ?? ()
#3  0x00007fffdc098440 in ?? () from /usr/lib/jvm/java-14-openjdk-amd64/lib/server/libjvm.so
#4  0x00007ffffff53eb0 in ?? ()
#5  0x00007fffdbcf074e in VM_Version::get_processor_features ()
    at ./src/hotspot/cpu/x86/vm_version_x86.cpp:580
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
</details>

**Comment by kevinushey** [comment]
Is there any hope of getting debug symbols? As far as I can see, the crash is occurring within OpenJDK.

**Comment by khaeru** [comment]
> Is there any hope of getting debug symbols?

"Installing debug symbols for all three languages hasn't helped pin down the cause." —to be less cryptic about this, I did install them:
```
openjdk-14-jre-headless:
  Installed: 14.0.1+7-1ubuntu1
  Candidate: 14.0.1+7-1ubuntu1
openjdk-14-dbg:
  Installed: 14.0.1+7-1ubuntu1
  Candidate: 14.0.1+7-1ubuntu1
```

However, as far as I can tell from the web, JDK debugging doesn't play nicely with GDB. I don't know how to use any other debuggers (I barely know how to use GDB, to be frank), but if there's a guide somewhere I can follow, I would be glad to do so.

**Comment by hadley** [comment]
Unfortunately I don't think there's much we can do to help you here 😞
